version: "3.9"

services:
  bring_coffee_db:
    image: postgres:latest
    container_name: bring_coffee_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_DOCKER_PORT}
    networks:
      - bring_coffee_network
    volumes:
      - bring_coffee_volume:/var/lib/postgresql/data

networks:
  bring_coffee_network:
    name: bring_coffee_network
    driver: bridge

volumes:
  bring_coffee_volume:
    name: bring_coffee_volume
